# Generated by Django 2.0.6 on 2018-10-11 04:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('timesheetApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='dateOfWork',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 11, 4, 38, 0, 438921, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='dateofEntry',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 11, 4, 38, 0, 438942, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='hours',
            field=models.IntegerField(default=datetime.datetime(2018, 10, 11, 4, 38, 31, 95689, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
