# Generated by Django 2.0.6 on 2018-10-11 04:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('timesheetApp', '0002_auto_20181011_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='dateOfWork',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 11, 4, 55, 15, 739976, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='dateofEntry',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 11, 4, 55, 15, 739999, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='hours',
            field=models.IntegerField(default=0),
        ),
    ]
